name: Telegram Bot

concurrency:
  group: telegram-bot
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y ffmpeg
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          LOG_CHANNEL_ID: ${{ secrets.LOG_CHANNEL_ID }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
        run: python bot_download.py